/*
   CLASS NAME: Order
   AUTHOR:     Oliver Huang
   DATE:       12/26/2019
   SCHOOL:     AY Jackson Secondary School
   PURPOSE:    A class that stores information of a order
*/

public class Order
{
   protected String username;
   protected String orderNumber;
   protected Driver driver;
   protected double amountPaid;
   protected int numOrders;
   protected boolean isCompelete = false;
   
   // Constructor /////////////////////////////////////////////////////////
   /*
      PARAMETERS:    username, driverID, amountPaid, numOrders
      RETURN VALUE:  N/A
      PURPOSE:       Creat order object
   */
   public Order (String username, Driver driver, double amountPaid, int numOrders)
   {
      this.username = username;
      this.amountPaid = amountPaid;
      this.numOrders = numOrders;
      //orderNumber = generated by UUID class
   }
   
   // Functions //////////////////////////////////////////////////////////////
   /*
      PARAMETERS:    N/A
      RETURN VALUE:  N/A
      PURPOSE:       mark order as compeleted
   */
   public void compeleteOrder ()
   {
      isCompelete = true;
   }
   //////////////////////////////////////////////////////////////
   /*
      PARAMETERS:    N/A
      RETURN VALUE:  Driver
      PURPOSE:       find driver who delivered this order
   */
   public Driver getDriver ()
   {
      return driver;
   }
   //////////////////////////////////////////////////////////
   public String toString ()
   {
      return orderNumber + "/n" + username + "/n" + amountPaid + "/n" + isCompelete;
   }
}